// Writes public/sitemap.xml from src/seo/indexable-routes.json, so the sitemap
// can never drift from the per-route head tags. Runs before vite build.
//
// Also fails loudly if a listed route is not declared in App.tsx, because a
// sitemap full of 404s is worse than no sitemap at all.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { site, routes } = JSON.parse(readFileSync(join(root, "src/seo/indexable-routes.json"), "utf8"));

// Cross-check against the router. Paths with params are skipped: none of ours use them.
const app = readFileSync(join(root, "src/app/App.tsx"), "utf8");
const declared = new Set([...app.matchAll(/path="([^"]*)"/g)].map((m) => m[1]));
const missing = routes.map((r) => r.path).filter((p) => !declared.has(p));
if (missing.length) {
  console.error(`\n  sitemap: these routes are listed for indexing but not declared in App.tsx:\n    ${missing.join("\n    ")}\n`);
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);
const body = routes
  .map((r) => `  <url><loc>${site}${r.path}</loc><lastmod>${today}</lastmod><priority>${r.priority}</priority></url>`)
  .join("\n");

writeFileSync(
  join(root, "public/sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by scripts/generate-sitemap.mjs. Do not edit: change src/seo/indexable-routes.json. -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`
);
console.log(`  sitemap: ${routes.length} routes, all verified against App.tsx`);
